"""Canonical ColdChain Guardian contracts: enums and Pydantic v2 schemas.

Source of truth: docs/CONTRACTS.md
"""

from .enums import (
    Assessment,
    CoverageStatus,
    DoorState,
    EventType,
    EvidenceKind,
    GenerationMode,
    HypothesisType,
    NextCheckCode,
    Outcome,
    PublicStage,
    RefrigerationState,
    ReviewDecision,
    RunStatus,
    SensorRole,
    StageEventStatus,
    VehicleState,
    VerificationStatus,
)
from .schemas import (
    MAX_SNAPSHOT_EVENTS,
    MAX_SNAPSHOT_READINGS,
    MAX_SNAPSHOT_SERIALIZED_BYTES,
    ArtifactRef,
    ClaimResult,
    CreateRunRequest,
    ErrorDetail,
    ErrorResponse,
    Event,
    EvidenceRef,
    HealthResponse,
    Hypothesis,
    NextCheck,
    Policy,
    QueueMessage,
    Reading,
    Report,
    Review,
    ReviewRequest,
    Run,
    RunResponse,
    RunSummary,
    Sensor,
    SensorMeasurement,
    Snapshot,
    StageEvent,
    StrictBase,
    Verification,
    snapshot_sha256,
)

__all__ = [
    # Enums
    "Assessment",
    "CoverageStatus",
    "DoorState",
    "EventType",
    "EvidenceKind",
    "GenerationMode",
    "HypothesisType",
    "NextCheckCode",
    "Outcome",
    "PublicStage",
    "RefrigerationState",
    "ReviewDecision",
    "RunStatus",
    "SensorRole",
    "StageEventStatus",
    "VehicleState",
    "VerificationStatus",
    # Constants
    "MAX_SNAPSHOT_EVENTS",
    "MAX_SNAPSHOT_READINGS",
    "MAX_SNAPSHOT_SERIALIZED_BYTES",
    # Schemas
    "ArtifactRef",
    "ClaimResult",
    "CreateRunRequest",
    "ErrorDetail",
    "ErrorResponse",
    "Event",
    "EvidenceRef",
    "HealthResponse",
    "Hypothesis",
    "NextCheck",
    "Policy",
    "QueueMessage",
    "Reading",
    "Report",
    "Review",
    "ReviewRequest",
    "Run",
    "RunResponse",
    "RunSummary",
    "Sensor",
    "SensorMeasurement",
    "Snapshot",
    "StageEvent",
    "StrictBase",
    "Verification",
    "snapshot_sha256",
]
