import { useState } from "react";
import { demoReport, demoRun, demoSnapshot } from "./mockData";
import { TelemetryChart } from "./TelemetryChart";
import { PrintableReport } from "./PrintableReport";
import { useRunData } from "./useRunData";
import { useOperatorActions } from "./useOperatorActions";
import { useAuth } from "../auth/AuthProvider";
import type { Report, Snapshot, ReviewDecision } from "../types/contracts";

const stageLabels: Record<string, string> = { preparing: "Preparing", detecting: "Detecting", collecting_evidence: "Collecting evidence", comparing_hypotheses: "Comparing hypotheses", verifying: "Verifying", ready: "Ready", failed: "Failed" };
type FixtureEvidenceItem = { key: string; title: string; detail: string; tone: "green" | "amber"; recordIds: string[] };
function formatTime(value: string) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" }).format(new Date(value)); }
function formatDuration(seconds: number | null) { return seconds == null ? "—" : `${Math.floor(seconds / 60)} min`; }
function MetricCard({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: "critical" | "review" | "info" }) { return <article className="rounded-[10px] border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-600">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className={`mt-1 text-[11px] font-medium ${tone === "critical" ? "text-red-700" : tone === "review" ? "text-amber-700" : "text-cyan-700"}`}>{detail}</p></article>; }
function outcomeCopy(report: Report) { if (report.outcome === "no_excursion") return { title: "No excursion detected", detail: "The deterministic measurements did not report an out-of-range excursion." }; if (report.outcome === "unresolved") return { title: "Investigation remains unresolved", detail: "Available evidence is insufficient to support a primary explanation." }; const finding = report.hypotheses.find((item) => item.hypothesis === report.primary_hypothesis); return { title: "Temperature exceeded the configured limit", detail: finding?.explanation ?? "A supported explanation is recorded in the report." }; }
function fixtureEvidence(snapshot: Snapshot): FixtureEvidenceItem[] { const door = snapshot.events.find((event) => event.event_type === "door_state"); const gap = snapshot.events.find((event) => event.value.includes("telemetry gap")); const reference = snapshot.sensors.find((sensor) => sensor.role === "reference"); const comparison = snapshot.sensors.find((sensor) => sensor.role === "comparison"); const peak = snapshot.readings.find((reading) => reading.sensor_id === reference?.sensor_id && reading.temperature_c > snapshot.policy.max_c); const comparisonReading = snapshot.readings.find((reading) => reading.sensor_id === comparison?.sensor_id); return [door && { key: door.event_id, title: "Door event", detail: `${formatTime(door.observed_at)} UTC · ${door.value}`, tone: "green" as const, recordIds: [door.event_id] }, peak && { key: peak.event_id, title: "Temperature peak", detail: `${peak.temperature_c}°C · Sensor A`, tone: "green" as const, recordIds: [peak.event_id] }, comparisonReading && { key: comparisonReading.event_id, title: "Sensor B", detail: `${comparisonReading.temperature_c}°C · comparison`, tone: "amber" as const, recordIds: [comparisonReading.event_id] }, gap && { key: gap.event_id, title: "Data gap", detail: `${formatTime(gap.observed_at)} UTC · ${gap.value}`, tone: "amber" as const, recordIds: [gap.event_id] }].filter((item): item is FixtureEvidenceItem => Boolean(item)); }

export function DashboardPage() {
  const auth = useAuth(); const live = useRunData(); const runId = live.source === "api" ? live.run.run_id : null; const actions = useOperatorActions(runId); const [selectedRecordIds, setSelectedRecordIds] = useState<Set<string>>(new Set()); const [reviewNote, setReviewNote] = useState(""); const [reviewDecision, setReviewDecision] = useState<ReviewDecision | null>(null);
  if (live.source === "api" && (!live.snapshotReady || !live.reportReady)) return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-[900px] p-5 lg:p-10"><section className="rounded-xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Live investigation</p><h1 className="mt-2 text-2xl font-semibold">{live.run.status === "failed" ? "Investigation failed" : "Investigation in progress"}</h1><p className="mt-2 text-sm leading-6 text-slate-600">Run {live.run.run_id} is at the <span className="font-semibold">{stageLabels[live.run.stage] ?? live.run.stage}</span> stage.</p>{live.error && <div role="alert" className="mt-6 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-xs font-medium text-red-800">{live.error.message}</div>}<button type="button" onClick={live.retry} className="mt-6 rounded-md border border-slate-200 px-3 py-2 text-xs font-semibold text-[#123B5D]">Retry</button></section></div></main>;
  const run = live.source === "api" ? live.run : demoRun; const snapshot = live.source === "api" ? live.snapshot : demoSnapshot; const report = live.source === "api" ? live.report : demoReport; const primaryMeasurement = report.measurements[0]; const copy = outcomeCopy(report); const finding = report.hypotheses.find((item) => item.hypothesis === report.primary_hypothesis); const evidence = report.evidence.length > 0 ? report.evidence : fixtureEvidence(snapshot); const isLive = live.source === "api"; const isReportReady = isLive ? (live.run.status === "completed" || live.run.status === "needs_review") && live.snapshotReady && live.reportReady : true; const currentReview = actions.review ?? run.review; const verificationCopy = report.verification.status === "passed" ? "Evidence references and measurements checked" : "Verification blocked";
  const handleRun = async () => { try { if (!auth.authenticated) { await auth.signIn(); return; } await actions.createRun(); } catch {} }; const handleReview = async (decision: ReviewDecision) => { if (!isLive || !reviewNote.trim() || actions.reviewSubmitting) return; setReviewDecision(null); try { await actions.submitReview({ decision, note: reviewNote.trim(), report_id: report.report_id }); setReviewDecision(decision); } catch {} }; const handleDownload = async () => { if (!isLive) return; try { await actions.downloadReport(); } catch {} };
  return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-[1440px] p-5 lg:p-8">{live.source === "fixture" && <div role="status" className="dashboard-chrome mb-3 rounded-md border border-amber-200 bg-amber-50 px-4 py-2 text-xs font-medium text-amber-800">Demo fixture mode — no live backend data is being shown.</div>}{live.error && <div role="alert" aria-live="assertive" className="dashboard-chrome mb-3 rounded-md border border-red-200 bg-red-50 px-4 py-2 text-xs font-medium text-red-800">{live.error.message}</div>}{actions.error && <div role="alert" aria-live="assertive" className="dashboard-chrome mb-3 rounded-md border border-red-200 bg-red-50 px-4 py-2 text-xs font-medium text-red-800">{actions.error.message}</div>}{auth.error && <div role="alert" aria-live="assertive" className="dashboard-chrome mb-3 rounded-md border border-red-200 bg-red-50 px-4 py-2 text-xs font-medium text-red-800">{auth.error.message}</div>}
  <header className="dashboard-chrome flex flex-wrap items-center gap-4 rounded-[10px] border border-slate-200 bg-white px-6 py-4 shadow-sm"><div className="min-w-[240px] flex-1"><h1 className="text-xl font-semibold">ColdChain Guardian</h1><p className="text-xs text-slate-400">Simulated shipment · AWS-backed processing</p></div><label className="text-xs font-semibold text-slate-600">Demo case<select aria-label="Demo case" defaultValue="door" className="ml-2 rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-normal text-slate-950"><option value="door">Door exposure · Run 1042</option></select></label><button type="button" onClick={() => void handleRun()} disabled={auth.loading} className="rounded-md bg-[#123B5D] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-60">{auth.loading ? "Checking session…" : "Run investigation"}</button><button type="button" onClick={() => window.print()} className="rounded-md border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-[#123B5D]" aria-label="Print investigation report">Print report</button></header>
  <div className="dashboard-chrome flex flex-wrap gap-x-6 gap-y-2 px-1 py-3 text-xs"><span className="font-semibold text-slate-600">Shipment {run.shipment_id.slice(-8)}</span><span className="text-slate-600">Policy {snapshot.policy.policy_id}-{snapshot.policy.policy_version} · {snapshot.policy.min_c}°C–{snapshot.policy.max_c}°C</span><span className="text-slate-400">Cutoff {new Date(snapshot.cutoff_at).toLocaleDateString("en-GB")} · {formatTime(snapshot.cutoff_at)} UTC</span><span className="rounded px-2 py-1 font-semibold text-amber-700 bg-amber-50">SIMULATED</span></div>
  <div className="dashboard-content"><section aria-label="Investigation summary" className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Observed peak" value={primaryMeasurement?.observed_max_c == null ? "—" : `${primaryMeasurement.observed_max_c}°C`} detail={primaryMeasurement?.observed_max_c != null && primaryMeasurement.observed_max_c > snapshot.policy.max_c ? "Above configured limit" : "Within configured limit"} tone={primaryMeasurement?.observed_max_c != null && primaryMeasurement.observed_max_c > snapshot.policy.max_c ? "critical" : "info"} /><MetricCard label="Estimated time out of range" value={formatDuration(primaryMeasurement?.estimated_out_of_range_seconds ?? null)} detail="Backend measurement" tone="review" /><MetricCard label="Data coverage" value={primaryMeasurement?.coverage_status ?? "—"} detail={primaryMeasurement?.unknown_duration_seconds ? `${formatDuration(primaryMeasurement.unknown_duration_seconds)} unknown` : "No unknown duration reported"} tone="info" /><MetricCard label="Review status" value={currentReview ? `Reviewed · ${currentReview.decision}` : report.review_required ? "Needs review" : "No review required"} detail={verificationCopy} tone={report.review_required && !currentReview ? "review" : "info"} /></section>
  <section className="mt-3"><TelemetryChart snapshot={snapshot} highlightedRecordIds={selectedRecordIds} onRecordSelect={(ids) => setSelectedRecordIds(new Set(ids))} /></section>
  <section className="mt-3 grid gap-3 lg:grid-cols-3"><article className="rounded-[10px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Investigation stages</h2><div className="mt-5 space-y-3">{run.stage_events.length > 0 ? run.stage_events.map((stage) => <div key={stage.event_id} className="flex items-center gap-3"><span aria-hidden="true" className={`h-2.5 w-2.5 rounded-full ${stage.status === "failed" ? "bg-red-700" : stage.status === "completed" ? "bg-green-700" : "bg-amber-600"}`} /><span className="flex-1 text-xs font-semibold">{stageLabels[stage.stage]}</span><span className="text-[11px] text-slate-500">{stage.status}</span></div>) : <span className="text-xs">{stageLabels[run.stage]}</span>}</div></article><article className="rounded-[10px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Main finding</h2><p className="mt-4 text-sm font-semibold text-red-700">{copy.title}</p><p className="mt-2 text-xs leading-5 text-slate-600">{copy.detail}</p>{finding && <p className="mt-2 text-[11px] text-amber-700">Evidence supports the hypothesis but does not establish disposition.</p>}<h3 className="mt-4 text-xs font-semibold text-slate-600">Next checks</h3><ul className="mt-2 space-y-2 text-xs">{report.next_checks.map((check) => <li key={check.code}>• {check.reason}</li>)}</ul></article><article className="rounded-[10px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Supporting &amp; conflicting evidence</h2><div className="mt-4 space-y-2">{evidence.map((item) => { const ids = "evidence_id" in item ? item.record_ids : item.recordIds; const active = ids.some((id) => selectedRecordIds.has(id)); const title = "evidence_id" in item ? item.summary : item.title; return <button key={"evidence_id" in item ? item.evidence_id : item.key} type="button" aria-pressed={active} onClick={() => setSelectedRecordIds(new Set(ids))} className={`w-full rounded-md p-3 text-left ${active ? "bg-amber-50 ring-1 ring-amber-300" : "bg-slate-50"}`}><p className="text-[11px] font-semibold">{title}</p></button>; })}</div></article></section>
  <section className="dashboard-chrome mt-3 grid gap-3 lg:grid-cols-[2fr_1fr]"><article className="rounded-[10px] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold">Operator review</h2><div className="mt-3 flex gap-2"><button type="button" disabled={!isLive || !reviewNote.trim() || actions.reviewSubmitting || Boolean(currentReview)} onClick={() => void handleReview("acknowledged")} className="rounded-md bg-[#123B5D] px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-50">Acknowledge review</button><button type="button" disabled={!isLive || !reviewNote.trim() || actions.reviewSubmitting || Boolean(currentReview)} onClick={() => void handleReview("request_more_evidence")} className="rounded-md border border-slate-200 px-3 py-2 text-[11px] font-semibold text-[#123B5D] disabled:opacity-50">Request evidence</button></div><textarea value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} maxLength={1000} placeholder="Add review note…" aria-label="Review note" className="mt-3 h-14 w-full rounded-md border border-slate-200 bg-slate-50 p-3 text-xs" /><p className="mt-1 text-right text-[10px] text-slate-400" aria-live="polite">{reviewNote.length}/1000</p>{reviewDecision && <p role="status" className="mt-2 text-[11px] text-green-700">Review saved.</p>}</article><article className="rounded-[10px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold">Report ready</h2><p className={`text-[10px] ${report.verification.status === "passed" ? "text-green-700" : "text-amber-700"}`}>{verificationCopy}</p></div><button type="button" disabled={!isLive || !isReportReady} onClick={() => void handleDownload()} className="rounded-md bg-[#123B5D] px-3 py-2 text-[11px] font-semibold text-white disabled:opacity-50">Download</button></div><details className="mt-3"><summary className="cursor-pointer text-[10px] font-semibold">Diagnostics</summary><p className="mt-2 text-[10px] text-slate-500">Run ID: {run.run_id}</p><p className="text-[10px] text-slate-500">Report ID: {report.report_id}</p></details></article></section></div>
  <PrintableReport run={run} snapshot={snapshot} report={report} reviewOverride={currentReview} />
  </div></main>;
}
